### ISSUE TITLE
Compile failed on windows

### ISSUE THREAD

**Issue by huangyt** [opensourcecheemsburgers/RustyTube#25]
cmd: cargo tauri build

Rebuilding...
Error: Cannot find module 'daisyui'
Require stack:
- D:\refproj\RustyTube\frontend\tailwind.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Function.resolve (C:\snapshot\tailwindcss\standalone-cli\patch-require.js:34:38)
    at _resolve (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:250334)
    at jiti (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:252917)
    at D:\refproj\RustyTube\frontend\tailwind.config.js:8:9
    at evalModule (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:255614)
    at jiti (C:\snapshot\tailwindcss\node_modules\jiti\dist\jiti.js:1:253542)
    at C:\snapshot\tailwindcss\lib\lib\load-config.js:48:30 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\refproj\\RustyTube\\frontend\\tailwind.config.js' ]
}
2024-03-02T11:52:50.014725Z  INFO calling wasm-bindgen for frontend
2024-03-02T11:52:50.136606Z  INFO calling wasm-opt
2024-03-02T11:52:51.974167Z  INFO rust build complete
2024-03-02T11:52:51.976874Z ERROR error
error from build pipeline

Caused by:
    0: HTML build pipeline failed (1 errors), showing first
    1: error from asset pipeline
    2: tailwindcss call to executable 'C:\Users\AppData\Local\trunkrs\trunk\cache\tailwindcss-3.4.1\tailwindcss.exe' with args: '["--input", "D:refproj\\RustyTube\\frontend\\css\\input.css", "--output", "D:\\refproj\\RustyTube\\frontend\\dist\\.stage\\input.css", "--minify"]' returned a bad status: exit code: 1
Error: error from build pipeline

Caused by:
    0: HTML build pipeline failed (1 errors), showing first
    1: error from asset pipeline
    2: tailwindcss call to executable 'C:\Users\AppData\Local\trunkrs\trunk\cache\tailwindcss-3.4.1\tailwindcss.exe' with args: '["--input", "D:\\refproj\\RustyTube\\frontend\\css\\input.css", "--output", "D:\\refproj\\RustyTube\\frontend\\dist\\.stage\\input.css", "--minify"]' returned a bad status: exit code: 1
       Error beforeBuildCommand `cd frontend && trunk build` failed with exit code 1

**Comment by huangyt** [comment]
Error: Cannot find module 'daisyui', how to fix that? thx !!!!

**Comment by opensourcecheemsburgers** [comment]
`cd frontend; npm install`
